SELECT
    II.ITEM_ID,
    II.ITEM_NAME,
    II.RARITY
FROM ITEM_INFO AS II
    JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
    JOIN ITEM_INFO AS P ON P.ITEM_ID = IT.PARENT_ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;