-- :SELECT: ID(ID)와 자식의 수(CHILD_COUNT)를 출력하는 SQL 문을 작성해주세요. 자식이 없다면 자식의 수는 0으로 출력
-- :FROM: ECOLI_DATA

SELECT
    PARENT.ID,
    COUNT(CHILD.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
LEFT JOIN ECOLI_DATA AS CHILD
    ON PARENT.ID = CHILD.PARENT_ID
GROUP BY PARENT.ID
ORDER BY PARENT.ID ASC;