WITH ELCOLI_CTE AS (
    SELECT
        *,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_ID,
        COUNT(*) OVER () AS ALL_COUNT
    FROM ECOLI_DATA
)
SELECT
    ID,
    CASE
        WHEN SIZE_ID <= ALL_COUNT * 0.25 THEN 'CRITICAL'
        WHEN SIZE_ID <= ALL_COUNT * 0.50 THEN 'HIGH'
        WHEN SIZE_ID <= ALL_COUNT * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ELCOLI_CTE
ORDER BY ID ASC;

SELECT
    ID,
    CASE
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 1 THEN 'CRITICAL'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 2 THEN 'HIGH'
        WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC;