WITH RECURSIVE GENERATIONS AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENE
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
        
    SELECT
        e.ID,
        e.PARENT_ID,
        g.GENE + 1
    FROM ECOLI_DATA AS E
        JOIN GENERATIONS AS g
            ON e.PARENT_ID = g.ID
)
SELECT
    COUNT(CASE WHEN C.id IS NULL THEN 1 END) AS COUNT,
    GE.GENE AS GENERATION
FROM ECOLI_DATA AS P
    LEFT JOIN ECOLI_DATA AS C
        ON P.id = C.PARENT_ID
    JOIN GENERATIONS AS GE
        ON GE.ID = P.ID
GROUP BY GE.GENE
ORDER BY GE.GENE
;

WITH RECURSIVE GENERATIONS AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENE
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
        
    SELECT
        e.ID,
        e.PARENT_ID,
        g.GENE + 1
    FROM ECOLI_DATA AS E
        JOIN GENERATIONS AS g
            ON e.PARENT_ID = g.ID
)
SELECT
    COUNT(*) AS COUNT,             
    GE.GENE AS GENERATION
FROM GENERATIONS AS GE
WHERE NOT EXISTS (                
    SELECT 1 
    FROM ECOLI_DATA 
    WHERE PARENT_ID = GE.ID
)
GROUP BY GE.GENE
ORDER BY GE.GENE;